# Site Settings
title: Desired Persona
email: your-email@domain.com
description: Your awesome site
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
date_format: "%-d %b %Y"


# Theme Settings
theme: minimal-jekyll-theme
twitter_username: desiredpersona


# Author Bio
show_author_bio: true
author:
    name: Desired Persona
    name_url: /about/
    bio: Affiliate marketer. Media buyer. Developer.
    button: Subscribe
    button_url: /newsletter/


# Post Meta Data
post:
    updated: 'Updated'
    minute_read: 'Min Read'


# Disqus Comments
disqus:
    shortname: jekyll-theme-dev
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.


# Tracking
google_analytics: UA-XXXXXXXX-N
google_tag_manager:
google_plus_id:
bing_verification:


# Build Settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

permalink: /:title/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
