source "https://rubygems.org"

# Jekyll
gem "jekyll", "3.3.0"

# Theme
gem "minimal-jekyll-theme" , :path => "../"

# Plugins
group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
  gem 'jekyll-admin'
  gem 'jemoji'
end
